/**
 * Database Views Migration
 * Creates all database views for enhanced data access
 * Consolidates: 005-create-patient-list-view, 006-create-patient-observations-view, 009-update-patient-observations-view-with-concept-description
 */

export const databaseViews = {
  name: '002-views',
  description: 'Create all database views with resolved concept names and descriptions',
  execute: async (connection) => {
    const statements = [
      // Drop existing views for clean recreation
      'DROP VIEW IF EXISTS patient_list',
      'DROP VIEW IF EXISTS patient_observations',

      // Create patient_list view with resolved concept names
      `CREATE VIEW patient_list AS
SELECT
    PATIENT_DIMENSION.PATIENT_NUM as PATIENT_NUM,
    PATIENT_DIMENSION.PATIENT_CD as PATIENT_CD,
    PATIENT_DIMENSION.IMPORT_DATE as IMPORT_DATE,
    PATIENT_DIMENSION.UPDATE_DATE as UPDATE_DATE,
    PATIENT_DIMENSION.BIRTH_DATE as BIRTH_DATE,
    PATIENT_DIMENSION.DEATH_DATE as DEATH_DATE,
    PATIENT_DIMENSION.AGE_IN_YEARS as AGE_IN_YEARS,
    PATIENT_DIMENSION.SEX_CD as SEX_CD,
    SEX.NAME_CHAR as SEX_RESOLVED,
    PATIENT_DIMENSION.VITAL_STATUS_CD as VITAL_STATUS_CD,
    STATUS.NAME_CHAR as VITAL_STATUS_RESOLVED,
    PATIENT_DIMENSION.LANGUAGE_CD as LANGUAGE_CD,
    LANG.NAME_CHAR as LANGUAGE_RESOLVED,
    PATIENT_DIMENSION.RACE_CD as RACE_CD,
    RACE.NAME_CHAR as RACE_RESOLVED,
    PATIENT_DIMENSION.MARITAL_STATUS_CD as MARITAL_STATUS_CD,
    MARITAL.NAME_CHAR as MARITAL_STATUS_RESOLVED,
    PATIENT_DIMENSION.RELIGION_CD as RELIGION_CD,
    REL.NAME_CHAR as RELIGION_RESOLVED,
    PATIENT_DIMENSION.STATECITYZIP_PATH as STATECITYZIP_PATH,
    PATIENT_DIMENSION.PATIENT_BLOB as PATIENT_BLOB,
    PATIENT_DIMENSION.SOURCESYSTEM_CD as SOURCESYSTEM_CD,
    PATIENT_DIMENSION.UPLOAD_ID as UPLOAD_ID,
    PATIENT_DIMENSION.CREATED_AT as CREATED_AT,
    PATIENT_DIMENSION.UPDATED_AT as UPDATED_AT
FROM
    PATIENT_DIMENSION
LEFT JOIN CONCEPT_DIMENSION AS SEX ON SEX.CONCEPT_CD = PATIENT_DIMENSION.SEX_CD
LEFT JOIN CONCEPT_DIMENSION AS STATUS ON STATUS.CONCEPT_CD = PATIENT_DIMENSION.VITAL_STATUS_CD
LEFT JOIN CONCEPT_DIMENSION AS LANG ON LANG.CONCEPT_CD = PATIENT_DIMENSION.LANGUAGE_CD
LEFT JOIN CONCEPT_DIMENSION AS RACE ON RACE.CONCEPT_CD = PATIENT_DIMENSION.RACE_CD
LEFT JOIN CONCEPT_DIMENSION AS MARITAL ON MARITAL.CONCEPT_CD = PATIENT_DIMENSION.MARITAL_STATUS_CD
LEFT JOIN CONCEPT_DIMENSION AS REL ON REL.CONCEPT_CD = PATIENT_DIMENSION.RELIGION_CD
ORDER BY PATIENT_CD`,

      // Create patient_observations view with resolved concept names and descriptions
      `CREATE VIEW patient_observations AS
SELECT
    PATIENT_DIMENSION.PATIENT_CD as PATIENT_CD,
    PATIENT_DIMENSION.PATIENT_NUM as PATIENT_NUM,
    VISIT_DIMENSION.ENCOUNTER_NUM as ENCOUNTER_NUM,
    OBSERVATION_FACT.START_DATE as START_DATE,
    OBSERVATION_FACT.OBSERVATION_ID as OBSERVATION_ID,
    OBSERVATION_FACT.CATEGORY_CHAR as CATEGORY_CHAR,
    OBSERVATION_FACT.CONCEPT_CD as CONCEPT_CD,
    CD1.NAME_CHAR as CONCEPT_NAME_CHAR,
    CD1.CONCEPT_BLOB as CONCEPT_DESCRIPTION,
    OBSERVATION_FACT.VALTYPE_CD as VALTYPE_CD,
    OBSERVATION_FACT.NVAL_NUM as NVAL_NUM,
    OBSERVATION_FACT.UNIT_CD as UNIT_CD,
    CD3.NAME_CHAR as UNIT_RESOLVED,
    OBSERVATION_FACT.TVAL_CHAR as TVAL_CHAR,
    CD2.NAME_CHAR as TVAL_RESOLVED,
    OBSERVATION_FACT.OBSERVATION_BLOB as OBSERVATION_BLOB,
    OBSERVATION_FACT.LOCATION_CD as LOCATION_CD,
    OBSERVATION_FACT.PROVIDER_ID as PROVIDER_ID,
    OBSERVATION_FACT.END_DATE as END_DATE,
    OBSERVATION_FACT.INSTANCE_NUM as INSTANCE_NUM,
    OBSERVATION_FACT.VALUEFLAG_CD as VALUEFLAG_CD,
    OBSERVATION_FACT.QUANTITY_NUM as QUANTITY_NUM,
    OBSERVATION_FACT.CONFIDENCE_NUM as CONFIDENCE_NUM,
    OBSERVATION_FACT.UPDATE_DATE as UPDATE_DATE,
    OBSERVATION_FACT.DOWNLOAD_DATE as DOWNLOAD_DATE,
    OBSERVATION_FACT.IMPORT_DATE as IMPORT_DATE,
    OBSERVATION_FACT.SOURCESYSTEM_CD as SOURCESYSTEM_CD,
    OBSERVATION_FACT.UPLOAD_ID as UPLOAD_ID
FROM
    OBSERVATION_FACT
INNER JOIN PATIENT_DIMENSION ON
    PATIENT_DIMENSION.PATIENT_NUM = OBSERVATION_FACT.PATIENT_NUM
INNER JOIN VISIT_DIMENSION ON
    VISIT_DIMENSION.ENCOUNTER_NUM = OBSERVATION_FACT.ENCOUNTER_NUM
LEFT JOIN CONCEPT_DIMENSION AS CD1 ON
    CD1.CONCEPT_CD = OBSERVATION_FACT.CONCEPT_CD
LEFT JOIN CONCEPT_DIMENSION AS CD2 ON
    CD2.CONCEPT_CD = OBSERVATION_FACT.TVAL_CHAR
LEFT JOIN CONCEPT_DIMENSION AS CD3 ON
    CD3.CONCEPT_CD = OBSERVATION_FACT.UNIT_CD
ORDER BY PATIENT_CD, ENCOUNTER_NUM, START_DATE, CONCEPT_NAME_CHAR`,
    ]

    // Execute each statement individually
    for (const statement of statements) {
      await connection.executeCommand(statement)
    }
  },
}
